commerce_invoice.settings:
  type: config_entity
  label: Settings
  mapping:
    invoice_number_generator:
      type: string
      label: 'Invoice number generator'
    invoice_number_padding:
      type: integer
      label: 'Invoice number padding'
    invoice_number_pattern:
      type: string
      label: 'Invoice number pattern'
    invoice_number_start:
      type: integer
      label: 'Invoice number start'
    invoice_due_date_days:
      type: integer
      label: 'Invoice due date days'
